### ISSUE TITLE
The shortcut switched with zoom in short cut on 50.2

### ISSUE THREAD

**Issue by lucky13820** [lukasoppermann/browser-preview#1]
Hi Lukas,

After installing the plugin on Sketch 50.2, the shortcut of zoom in is switched with the shortcut for browser preview. Now, I need to use shift command + to zoom in, and command + to preview in browser. I don't know why this happened. Can you look into this?

**Comment by lukasoppermann** [comment]
hey @lucky13820 you are saying by default the shortcut for browser preview is `cmd +`? This would be very weird. Do you have any plugins installed? It works fine for me and the shortcut is defined in the code, so it should not change.

However, if no plugin interferes you may want to try https://github.com/exevil/Keys-For-Sketch which lets you change the shortcuts. Maybe this solves it?

**Comment by lucky13820** [comment]
I know, it's really weird. I have quite a lot plugins installed, but disabling the plugins didn't fix the issue. I will try the Keys plugin. Maybe there is something wrong with my computer.

**Comment by corbinmuraro** [comment]
Bumping this, as I'm having the same issue  — the plugin is being run on `cmd +`, overriding the zoom in shortcut native to Sketch. Consequently, I'm disabling the plugin whenever I'm making edits, and then briefly enabling it and `cmd +`ing to preview in browser. I'm running 50.2.

I'll give Keys a try to switch the plugin shortcut, but would love for both to work without the fix.

**Comment by lukasoppermann** [comment]
Hey folks,

I have a hard time reproducing this issue. I just reinstalled the plugin via runner and via the bundle and it works fine in both cases. 

Can you give me some more info?
- How did you install it?
- What language do you use on your mac?
- Do you have any plugin that uses this keyboard shortcut already?
- Do you have plugin that changes shortcuts?

**Comment by corbinmuraro** [comment]
All of my answers are the same as lucky's — installed through Sketch Runner, English language, and I don't have any plugins that use this shortcut. I just tried to disable all plugins and restart sketch to no avail. 

I also tried to install directly via the `.sketchplugin` instead of through Sketch Runner, but had the same issue. Super weird.

**Comment by lukasoppermann** [comment]
Just to make sure: does removing the plugin revert the shortcuts?

**Comment by corbinmuraro** [comment]
Yeah, it does — really strange.

**Comment by lukasoppermann** [comment]
Okay, hmm. I have to say that I really don't know what to do, as I can't even reproduce it and we have no idea what causes this complication.

I actually have the exact same setup as you two and it works fine for me. So if you find anything in common that could cause it or have any ideas I am happy to try it.

**Comment by lukasoppermann** [comment]
**Done in v2.2.0**

- by default it is now cmd + shift + p, however you should be able to choose it with the mac keyboard settings
