### ISSUE TITLE
Artboard with Chinese Name would preview in Safari

### ISSUE THREAD

**Issue by lucky13820** [lukasoppermann/browser-preview#2]
Any artboard that has Chinese name will not preview in Safari. I need to change the name to English in order to work, or I have to copy the link to Chrome. The screenshot shows the same artboard with the different names. The one with the Chinese name shows some gibberish, English is fine. Feels like it relates to the encoding. Can you please have a look? 
![screen shot 2018-08-08 at 4 28 36 pm](https://user-images.githubusercontent.com/7293811/43869639-6919737a-9b28-11e8-8bdf-72c8dd91993e.png)
![screen shot 2018-08-08 at 4 28 38 pm](https://user-images.githubusercontent.com/7293811/43869640-692edbf2-9b28-11e8-95c7-3636cfadfcc3.png)

**Comment by lukasoppermann** [comment]
Thank you for reporting, this has been fixed in 2.0.8.
