### ISSUE TITLE
Artboard name is url encoded which breaks preview when using / in the name.

### ISSUE THREAD

**Issue by esiao** [lukasoppermann/browser-preview#25]
Hello @lukasoppermann, first off thank you for a great and super useful plugin.
I recently ran into an issue that I never noticed because I didn't use the feature before.

Sketch allows exporting files to a folder directly by using a / in the name.
ie: desktop/my-layout

When using the plugin it'll load the webpage but the link to the image is broken as it's
`desktop%2Fmy-layout` instead of `desktop/my-layout` to target the folder created by Sketch.

I suppose it's a quick fix
https://github.com/lukasoppermann/browser-preview/blob/master/src/create-preview.js#L17

By replacing `%2F` with `/` in the `artboard.name`.

Let me know how you would fix this slight issue.

**Comment by lukasoppermann** [comment]
Hey @esiao that sounds good. Could you send a PR for this?

And if you do, could you also fix this: https://github.com/lukasoppermann/browser-preview/blob/master/src/create-preview.js#L47 the `img` tag seems to be missing the closing bracket ">".

Happy to merge it.

**Comment by HPieters** [comment]
Had the same issue and took the liberty of making a PR, didn't know how to test it locally though.
