### ISSUE TITLE
Update MacOS catalina, plugin can't work correctly

### ISSUE THREAD

**Issue by houyining** [lukasoppermann/browser-preview#7]
Preview Artboard will show the "creating tips", but can't open browser when updating macOS system to catalina.

**Comment by houyining** [comment]
@lukasoppermann

**Comment by houyining** [comment]
![image](https://user-images.githubusercontent.com/3396931/66409954-ddf3ad00-ea23-11e9-9741-d017e3c0b737.png)

**Comment by lukasoppermann** [comment]
Hey @houyining is this issue still persisting? I would guess that this would either be an issue with permissions or with the encoding. Did it work for you before updating to Catalina?

**Comment by houyining** [comment]
Yes, it works well before updating to Catalina.

**Comment by lukasoppermann** [comment]
And you are using the same language after the update?

**Comment by razer-k** [comment]
I'm very happy with this plugin, especially on a retina display. But I have a slight problem. I'm using the Yandex Browser but I can't choose it in the Plugin settings. Could you add the option "Use system/user browser" or something similar? Thank you, anyway!
