### ISSUE TITLE
Make Sound Effect Optional

### ISSUE THREAD

**Issue by mittelgrau** [lukasoppermann/browser-preview#9]
The Plugins works great, thank you for that. Would it be possible to add another setting that makes the sound effect optional? Just a little enhancment

**Comment by lukasoppermann** [comment]
Hey @mittelgrau,
for this it would be required to write a custom settings screen. I would love that, but currently do not have the time. 

If you can pitch in and send a PR I would be more than happy to merge it.

**Comment by mittelgrau** [comment]
I'm not really familiar with Sketch Plugin Api but its a good chance to dig through it.  Already got the basic outline working. Will put some more time in it if i find the time. 
<img width="432" alt="preview image for setting" src="https://user-images.githubusercontent.com/30243035/76266582-3f84a580-6268-11ea-9829-159c177e398b.png">

**Comment by lukasoppermann** [comment]
Very nice, that looks really great. This will make it also easier later on to allow users to customize the shortcut. Looking forward to the PR.

**Comment by lukasoppermann** [comment]
Reopening as the feature is not published yet.
